### ISSUE TITLE
System blacklists is buggy, soundfont lists in wrong place ALPHA VERSION

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/Keppy-s-Driver#12]
Hi. The system blacklists is a little bit buggy. When I open a blacklisted program, it causes a fatal error (Sorry, I don't capture the dialog but I think it says that the default blacklist is missing). The only solution is to delete the blacklist to allow the driver to recreate it.
Also, when I search through the blacklist folder, I found that the soundfont lists are in there as well. I think that's why creating another "lists" folder for the configurator is needed.

PS: Can you give me the source code of the alpha? The version on the releases page is still 1.5.0.64.

**Comment by KaleidonKep99** [comment]
I know.
I figured it out by myself, when I restarted Windows.
The login screen gave me a FATAL ERROR, because it wasn't able to find the original blacklist. (Because I wasn't logged in)
I'm going to move the default blacklist back to X:\Windows.
About the soundfont lists being created in the "blacklist" folder:
It's actually my fault, because I mistyped the correct folder in the configurator's source code.

Also no, I can't.
Alphas and betas will be private until they don't reach the final stage.
